# Development configuration for the RAG Chatbot

document:
  chunk_size: 1000
  chunk_overlap: 200
  supported_formats:
    - "pdf"
    - "txt"
    - "md"
    - "html"
    - "docx"

embeddings:
  model: "sentence-transformers/all-MiniLM-L6-v2"
  dimension: 384
  batch_size: 16

vector_store:
  type: "faiss"
  index_path: "./data/vector_index"
  similarity_metric: "cosine"

retrieval:
  top_k: 5
  score_threshold: 0.7
  search_type: "similarity"
  mmr_lambda: 0.7

llm:
  provider: "openai"
  model: "gpt-3.5-turbo"
  max_tokens: 750
  temperature: 0.2

api:
  host: "127.0.0.1"
  port: 8000
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"

evaluation:
  metrics:
    - "answer_relevancy"
    - "context_relevancy"
    - "groundedness"
    - "faithfulness"
  test_data_path: "./data/eval_qa_pairs.json"

logging:
  level: "DEBUG"
  file: "./logs/rag_demo.dev.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
